/* SCAPE intro config — generated by the tune panel (press T).
   Load this before scape-intro.js, then: SCAPE.mount('.stage', SCAPE_CONFIG) */
window.SCAPE_CONFIG = {
  /* timing */
  style: 'quantum',
  duration: 5,
  lift: 38,
  reveal: 86,
  ease: 'ease-in-out',

  /* mark */
  charset: 'ascii',
  palette: 'spectrum',
  zoom: 1.7,
  density: 7,
  spread: 16,
  stagger: 42,
  churn: 22,
  turns: 1.5,
  noise: 240,

  /* ignite */
  solidify: true,
  igniteStyle: 'wave',
  igniteLen: 34,
  afterglow: 112,

  /* trip */
  trails: 18,
  bloom: 30,
  split: 34,
  drift: 40,

  /* background */
  bg: 'shaft',
  bgAmt: 26,
  bgSpeed: 100,
  bgScale: 2,
  bgColor: 'palette',
  bgHue: 200,
  bgPersist: false,

  /* pulse */
  pulse: 'corners',
  pulseEchoes: 2,
  pulseReach: 45,
  pulseThick: 2,
  pulseAmt: 20,
  pulseColor: 'mono',
  pulseHue: 200,

  /* parts */
  partsOn: false,
  partDelay: { ring: 0, barTop: 14, barBottom: 22, stemLeft: 34, stemRight: 44, dotLeft: 62, dotRight: 78 },

  /* buttons */
  btnFx: 'plasma',
  btnInt: 80,
  btnSpeed: 1,
  btnIdle: 22,
  btnCharPx: 6,
  invert: true,
  btnMono: true,
  btnInvertMode: 'none',
  btnAttack: 0.09,
  btnRelease: 0.22,

  /* behaviour */
  loop: false,
  skippable: false,
  pauseWhenHidden: true,
  reducedMotion: 'ignore',
  once: false
};
