/* SCAPE intro runtime — generated by build.py from src/. Do not hand-edit.
   No dependencies. Plain ES2020 — run it through your own minifier.

     SCAPE.mount('.stage', SCAPE_CONFIG)
     -> controller: .replay() .set(patch) .destroy() .serialize()
                    .skip() .pause() .resume() .finish()

   Markup: a .stage containing a .logo of .el1-.el6, and optionally .button
   elements to decorate. It appends its own <canvas class="ascii-canvas"> if
   one is not already present. See index.html. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.SCAPE = factory();
})(typeof self !== 'undefined' ? self : this, function () {
'use strict';
/* ═══════════════════════════════════════════════════════════════════════
   SCAPE — ascii intro engine
   The mark is an 11 x 9 module grid (identical to logo.png and to the
   .el1–.el6 boxes). Every character in the field lives on one shared grid
   whose origin is aligned to the mark, so converging chars always land on
   exact cells.
   ═══════════════════════════════════════════════════════════════════════ */
const MARK = [
  '###########',
  '#.........#',
  '#.#######.#',
  '#.#.......#',
  '#.#.#.#.#.#',
  '#.......#.#',
  '#.#######.#',
  '#.........#',
  '###########'
];
/* The same grid again, labelled by which piece of the mark each module belongs
   to, so the intro can draw the parts at different rates. Shared modules go to
   the bar that crosses them. */
const PARTS = [
  'RRRRRRRRRRR',
  'R.........R',
  'R.TTTTTTT.R',
  'R.L.......R',
  'R.L.a.b.S.R',
  'R.......S.R',
  'R.UUUUUUU.R',
  'R.........R',
  'RRRRRRRRRRR'
];
const PART_IDS = { R: 'ring', T: 'barTop', U: 'barBottom', L: 'stemLeft',
                   S: 'stemRight', a: 'dotLeft', b: 'dotRight' };
const MARK_W = 11, MARK_H = 9, MODULE = 16;   /* px per module at zoom 1 */
/* The mark is a rectangle, so the fields that orbit it should be too: this is
   the radius of the 11:9 rectangle a point sits on, standing in for the
   Euclidean radius a circular field would use. */
const RECT_AX = MARK_W / MARK_H;
const rectR = (dx, dy) => Math.max(Math.abs(dx) / RECT_AX, Math.abs(dy));
const BOX = '─│┌┐└┘├┤┬┴┼╌╎';
const WIRE = '─│┼└┘┌┐';
/* indexed by right(1) | down(2) | up(4) | left(8) */
const NODE = ['', '─', '│', '┌', '│', '└', '│', '├',
              '─', '─', '┐', '┬', '┘', '┴', '┤', '┼'];

/* Walk the mark's silhouette at any module size, emitting only the edges that
   border empty space. Shared by the echo pulse and the nest field. */
function eachMarkEdge(ox, oy, ms, th, cb) {
  for (let r = 0; r < MARK_H; r++) for (let c = 0; c < MARK_W; c++) {
    if (MARK[r].charAt(c) !== '#') continue;
    const x0 = Math.round(ox + c * ms), x1 = Math.round(ox + (c + 1) * ms) - 1;
    const y0 = Math.round(oy + r * ms), y1 = Math.round(oy + (r + 1) * ms) - 1;
    if (x1 < x0 || y1 < y0) continue;
    const up    = r > 0          && MARK[r - 1].charAt(c) === '#';
    const down  = r < MARK_H - 1 && MARK[r + 1].charAt(c) === '#';
    const left  = c > 0          && MARK[r].charAt(c - 1) === '#';
    const right = c < MARK_W - 1 && MARK[r].charAt(c + 1) === '#';
    for (let k = 0; k < th; k++) {
      if (!up)    for (let x = x0; x <= x1; x++) cb(x, y0 - k);
      if (!down)  for (let x = x0; x <= x1; x++) cb(x, y1 + k);
      if (!left)  for (let y = y0; y <= y1; y++) cb(x0 - k, y);
      if (!right) for (let y = y0; y <= y1; y++) cb(x1 + k, y);
    }
  }
}
const SOLID = '█';

const CHARSETS = {
  blocks: '█▓▒░▚▞▌▐▀▄■□',
  ascii : '.:-=+*#%@&$',
  wire  : '/\\|-_+*<>[]{}()=~^',
  binary: '01',
  matrix: 'アイウエオカキクケコサシスセソタチツテトナニヌネノ0123456789',
  runes : '◈◉◇◆▲▼◢◣⌒⌘◎▣',
  scape : 'SCAPE'
};

const PALETTES = {
  spectrum: { sat: 100, hue: r => r() * 360 },
  acid    : { sat: 100, hue: r => [95, 150, 300][(r() * 3) | 0] + r() * 34 },
  ember   : { sat: 100, hue: r => r() * 52 },
  ice     : { sat: 100, hue: r => 172 + r() * 92 },
  vapor   : { sat: 100, hue: r => [318, 188, 272][(r() * 3) | 0] + r() * 22 },
  mono    : { sat: 0,   hue: () => 0 }
};

/* deterministic per-replay randomness */
function rng(seed) {
  return function () {
    seed |= 0; seed = seed + 0x6D2B79F5 | 0;
    let t = Math.imul(seed ^ seed >>> 15, 1 | seed);
    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
/* stable 2-arg hash — lets a particle look up "what am I at tick N" without state */
function h2(a, b) {
  let t = (a * 374761393 + b * 668265263) | 0;
  t = Math.imul(t ^ t >>> 13, 1274126177);
  return ((t ^ t >>> 16) >>> 0) / 4294967296;
}

const clamp01 = x => x < 0 ? 0 : x > 1 ? 1 : x;
const smooth = p => p * p * (3 - 2 * p);
const eOutCubic = p => 1 - Math.pow(1 - p, 3);
const eInCubic = p => p * p * p;
const eInOutCubic = p => p < .5 ? 4 * p * p * p : 1 - Math.pow(-2 * p + 2, 3) / 2;
const eOutBack = p => { const c = 1.9; return 1 + (c + 1) * Math.pow(p - 1, 3) + c * Math.pow(p - 1, 2); };
const eOutExpo = p => p >= 1 ? 1 : 1 - Math.pow(2, -10 * p);
const eInOutExpo = p => p <= 0 ? 0 : p >= 1 ? 1 : p < .5
  ? Math.pow(2, 20 * p - 10) / 2 : (2 - Math.pow(2, -20 * p + 10)) / 2;
function wrapAngle(a) { while (a > Math.PI) a -= Math.PI * 2; while (a < -Math.PI) a += Math.PI * 2; return a; }

/* Phase boundaries, as a fraction of the splash duration.
     0 .......... tConv   every mark character has landed
     tConv ...... T_IGN   IGNITE: characters walk a density ramp and glow until
                          the mark saturates into a solid glowing shape
     T_IGN ...... +0.06   the (now identical) DOM mark takes over — invisible
     T_LIFT               the mark lifts
   tConv is derived from the ignite length, so a longer ignite eats into the
   converge window rather than running past the end. */
const T_IGN  = 0.88;
const T_LIFT = 0.90;

/* Ink-coverage ramp: render each glyph once and rank it by how much of its cell
   it actually fills. Gives a true sparse→dense ordering for ANY character set —
   katakana and runes included — so the ignite fills smoothly instead of
   snapping. Ends on the full block, which is exactly the solid mark. */
const RAMP_CACHE = {};
function rampFor(chars) {
  if (RAMP_CACHE[chars]) return RAMP_CACHE[chars];
  const c = document.createElement('canvas');
  c.width = c.height = 20;
  const x = c.getContext('2d', { willReadFrequently: true });
  x.font = '16px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace';
  x.textAlign = 'center'; x.textBaseline = 'middle';
  const scored = [];
  for (const ch of chars) {
    x.clearRect(0, 0, 20, 20);
    x.fillStyle = '#fff';
    x.fillText(ch, 10, 10);
    const d = x.getImageData(0, 0, 20, 20).data;
    let s = 0;
    for (let i = 3; i < d.length; i += 4) s += d[i];
    scored.push([ch, s]);
  }
  scored.sort((a, b) => a[1] - b[1]);
  return (RAMP_CACHE[chars] = scored.map(s => s[0]).join('') + SOLID);
}

class AsciiIntro {
  constructor(canvas) {
    this.cv = canvas;
    this.ctx = canvas.getContext('2d');
    this.oc = document.createElement('canvas');      /* per-frame draw buffer */
    this.octx = this.oc.getContext('2d');
    this.raf = 0;
    this.running = false;
    this.parts = [];
  }

  start(cfg) {
    this.halt();
    this.cfg = cfg;
    this.rand = rng((Math.random() * 1e9) | 0);
    this.layout();
    this.build();
    this.t0 = performance.now();
    this.last = this.t0;
    this.frames = 0;
    this.running = true;
    this.step = this.step.bind(this);
    this.raf = requestAnimationFrame(this.step);
  }
  halt() {
    if (this.raf) cancelAnimationFrame(this.raf);
    this.raf = 0; this.running = false;
    const c = this.ctx;
    c.setTransform(1, 0, 0, 1, 0, 0);
    c.clearRect(0, 0, this.cv.width, this.cv.height);
  }

  layout() {
    const cfg = this.cfg;
    if (!cfg) return;
    const dpr = this.dpr = Math.min(2, window.devicePixelRatio || 1);
    const w = this.w = Math.max(1, window.innerWidth), h = this.h = Math.max(1, window.innerHeight);
    for (const cv of [this.cv, this.oc]) {
      cv.width = Math.round(w * dpr); cv.height = Math.round(h * dpr);
    }
    const cell = this.cell = MODULE * cfg.zoom / cfg.density;
    this.font = Math.round(cell * 1.16) + 'px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace';
    const o = this.octx;
    o.setTransform(1, 0, 0, 1, 0, 0);
    o.font = this.font; o.textAlign = 'center'; o.textBaseline = 'middle';
    /* stretch every glyph to exactly one cell wide so the mark reads solid */
    this.xs = cell / (o.measureText(SOLID).width || cell * 0.6);

    /* align the grid so the mark's top-left corner is a cell boundary */
    const a = cfg.anchor();
    cfg.markX = a.x; cfg.markY = a.y;
    const k0 = Math.round(a.x / cell), l0 = Math.round(a.y / cell);
    this.ox = a.x - k0 * cell;
    this.oy = a.y - l0 * cell;
    this.mc0 = k0; this.mr0 = l0;
    this.gx0 = Math.floor(-this.ox / cell) - 1;
    this.gx1 = Math.ceil((w - this.ox) / cell) + 1;
    this.gy0 = Math.floor(-this.oy / cell) - 1;
    this.gy1 = Math.ceil((h - this.oy) / cell) + 1;
    this.gw = this.gx1 - this.gx0;
    this.gh = this.gy1 - this.gy0;
    this.bgSetup();
  }
  /* The helmet stylesheet and web fonts can land after mount, which moves the
     mark. For the first few frames, re-measure and slide the whole field (and
     every particle) onto the corrected origin rather than trusting mount-time
     layout. */
  reanchor() {
    const a = this.cfg.anchor();
    if (Math.abs(a.x - this.cfg.markX) < 0.5 && Math.abs(a.y - this.cfg.markY) < 0.5) return;
    const cell = this.cell;
    const k0 = Math.round(a.x / cell), l0 = Math.round(a.y / cell);
    const dc = k0 - this.mc0, dr = l0 - this.mr0;
    this.cfg.markX = a.x; this.cfg.markY = a.y;
    this.ox = a.x - k0 * cell; this.oy = a.y - l0 * cell;
    this.mc0 = k0; this.mr0 = l0;
    this.mcx += dc; this.mcy += dr;
    if (dc || dr) {
      for (const p of this.parts) { p.tx += dc; p.ty += dr; p.sx += dc; p.sy += dr; }
      this.gx0 = Math.floor(-this.ox / cell) - 1;
      this.gx1 = Math.ceil((this.w - this.ox) / cell) + 1;
      this.gy0 = Math.floor(-this.oy / cell) - 1;
      this.gy1 = Math.ceil((this.h - this.oy) / cell) + 1;
    }
  }

  px(gx) { return this.ox + (gx + 0.5) * this.cell; }
  py(gy) { return this.oy + (gy + 0.5) * this.cell; }

  build() {
    const cfg = this.cfg, R = this.rand, S = cfg.density;
    this.chars = CHARSETS[cfg.charset] || CHARSETS.blocks;
    this.pal = PALETTES[cfg.palette] || PALETTES.spectrum;

    const cells = [];
    for (let r = 0; r < MARK_H * S; r++)
      for (let c = 0; c < MARK_W * S; c++) {
        const mr = (r / S) | 0, mc = (c / S) | 0;
        if (MARK[mr].charAt(mc) !== '#') continue;
        cells.push([this.mc0 + c, this.mr0 + r, PART_IDS[PARTS[mr].charAt(mc)] || 'ring']);
      }

    this.mcx = this.mc0 + MARK_W * S / 2;
    this.mcy = this.mr0 + MARK_H * S / 2;

    /* ordering drives the stagger; rain wants column order, everything else
       looks better shuffled */
    if (cfg.partsOn) {
      /* draw order comes from the per-part delays, so ordering within a part
         is all that is left to shuffle */
      const rank = p => (cfg.partDelay[p[2]] || 0);
      cells.sort((a, b) => rank(a) - rank(b));
    } else if (cfg.variant === 'rain') cells.sort((a, b) => a[0] - b[0] || a[1] - b[1]);
    else for (let i = cells.length - 1; i > 0; i--) {
      const j = (R() * (i + 1)) | 0, t = cells[i]; cells[i] = cells[j]; cells[j] = t;
    }

    this.ramp = rampFor(this.chars);
    const P = this.parts = [];
    for (let i = 0; i < cells.length; i++)
      P.push(this.mk(cells[i][0], cells[i][1], i / cells.length, 1, cells[i][2]));
    /* per-cell ignite phase: 0 lights first, 1 lights last */
    const S2 = MARK_W * S / 2, S3 = MARK_H * S / 2;
    const rMax = Math.hypot(S2, S3) || 1;
    for (const p of P) {
      if (p.kind !== 1) continue;
      const dx = p.tx - this.mcx, dy = p.ty - this.mcy;
      p.phWave = clamp01(Math.hypot(dx, dy) / rMax);
      p.phScan = clamp01((p.ty - this.mr0) / (MARK_H * S));
      p.phRand = h2(p.seed, 4242);
    }

    /* Loose chars aim at the mark's centre but burn out well before they get
       there — they read as chatter being pulled in, without filling the mark. */
    for (let i = 0; i < cfg.noise; i++) {
      const a = R() * Math.PI * 2, rr = R() * Math.min(MARK_W, MARK_H) * S * 0.45;
      P.push(this.mk(this.mcx + Math.cos(a) * rr, this.mcy + Math.sin(a) * rr, R(), 0));
    }
    this.markCount = cells.length;
  }

  mk(tx, ty, order, kind, part) {
    const R = this.rand, cfg = this.cfg, V = cfg.variant;
    const p = { tx, ty, kind, part };
    p.hue = this.pal.hue(R);
    p.sat = this.pal.sat;
    p.fch = this.chars[(R() * this.chars.length) | 0];
    p.seed = (R() * 1e6) | 0;
    p.spin = R() * 2 - 1;
    p.K = 3 + R() * 11;

    const sg = cfg.stagger;
    if (cfg.partsOn && kind === 1) {
      /* each part starts at its own point in the converge window; the stagger
         slider still scatters the cells within a part so it does not arrive
         as one rigid block */
      const pd = clamp01((cfg.partDelay[part] || 0) / 100);
      p.delay = pd * 0.82 + R() * sg * 0.12;
      p.dur = Math.max(0.08, Math.min(1 - p.delay, 0.34 + R() * 0.22));
    } else {
      p.delay = order * sg * 0.88 + R() * sg * 0.2;
      p.dur = (1 - sg * 0.88) * (0.62 + R() * 0.42);
      if (p.delay + p.dur > 1) p.dur = Math.max(0.06, 1 - p.delay);
    }

    if (V === 'rain') {
      p.sx = tx; p.sy = this.gy0 - 2 - R() * this.gh * 1.1;
    } else if (V === 'warp') {
      p.sx = this.mcx + (tx - this.mcx) * p.K;
      p.sy = this.mcy + (ty - this.mcy) * p.K;
    } else if (V === 'decode') {
      p.sx = tx; p.sy = ty;
    } else {
      p.sx = this.gx0 + R() * this.gw;
      p.sy = this.gy0 + R() * this.gh;
    }
    p.aS = Math.atan2(p.sy - this.mcy, p.sx - this.mcx);
    p.rS = Math.hypot(p.sx - this.mcx, p.sy - this.mcy);
    p.aT = Math.atan2(ty - this.mcy, tx - this.mcx);
    p.rT = Math.hypot(ty - this.mcy, tx - this.mcx);
    p.dA = wrapAngle(p.aS - p.aT);
    return p;
  }

  /* where a particle sits at local progress q (0..1) */
  pos(p, q, t, out) {
    const cfg = this.cfg, V = cfg.variant, J = cfg.spread;
    let gx, gy;
    if (V === 'vortex') {
      const e = eInOutCubic(q);
      const turns = cfg.turns * (p.spin < 0 ? -1 : 1);
      const a = p.aT + (p.dA + turns * Math.PI * 2) * (1 - e);
      const r = p.rT + (p.rS - p.rT) * (1 - eOutCubic(q));
      gx = this.mcx + Math.cos(a) * r;
      gy = this.mcy + Math.sin(a) * r;
    } else if (V === 'warp') {
      const e = eInOutExpo(q);
      const f = p.K + (1 - p.K) * e;
      const ang = (1 - e) * cfg.turns * Math.PI * p.spin;
      const dx = p.tx - this.mcx, dy = p.ty - this.mcy;
      const ca = Math.cos(ang), sa = Math.sin(ang);
      gx = this.mcx + (dx * ca - dy * sa) * f;
      gy = this.mcy + (dx * sa + dy * ca) * f;
    } else if (V === 'rain') {
      const e = eInCubic(q);
      gx = p.tx; gy = p.sy + (p.ty - p.sy) * e;
    } else if (V === 'decode') {
      const e = eOutCubic(q), k = (1 - e) * (1 - e);
      const tick = Math.floor(t * 90 * this.cfg.churnRate);
      gx = p.tx + (h2(p.seed, tick) * 2 - 1) * J * k;
      gy = p.ty + (h2(p.seed, tick + 7717) * 2 - 1) * J * k * 0.7;
    } else if (V === 'storm') {
      const e = eInOutCubic(q);
      const dx = p.tx - p.sx, dy = p.ty - p.sy;
      const L = Math.hypot(dx, dy) || 1;
      const amp = Math.sin(q * Math.PI) * J * 0.55 * p.spin;
      const wob = Math.sin(q * Math.PI * (2 + cfg.turns * 2) + p.seed) * J * 0.18 * (1 - e);
      gx = p.sx + dx * e - dy / L * amp + wob;
      gy = p.sy + dy * e + dx / L * amp;
    } else if (V === 'glitch') {
      const e = Math.floor(eOutCubic(q) * 7) / 7;      /* teleport in 7 steps */
      const tick = Math.floor(q * 9);
      const band = Math.floor(p.ty / 2);
      const off = (h2(band * 31 + tick, 5) * 2 - 1) * J * 1.6 * (1 - eOutExpo(q));
      gx = p.sx + (p.tx - p.sx) * e + off;
      gy = p.sy + (p.ty - p.sy) * e;
    } else if (V === 'quantum') {
      const b = eInOutCubic(q);
      const steps = 5 + Math.floor(q * 30);
      const tick = Math.floor(q * steps);
      const rad = (1 - b) * J * 1.1;
      gx = p.sx + (p.tx - p.sx) * b + (h2(p.seed, tick) * 2 - 1) * rad;
      gy = p.sy + (p.ty - p.sy) * b + (h2(p.seed, tick + 991) * 2 - 1) * rad;
    } else { /* converge */
      const e = eOutBack(q);
      gx = p.sx + (p.tx - p.sx) * e;
      gy = p.sy + (p.ty - p.sy) * e;
    }
    if (q >= 1) { gx = p.tx; gy = p.ty; }
    out[0] = gx; out[1] = gy;
  }

  glyph(ch, x, y, color, alpha) {
    const o = this.octx, d = this.dpr;
    o.globalAlpha = alpha;
    o.fillStyle = color;
    o.setTransform(d * this.xs, 0, 0, d, d * x, d * y);
    o.fillText(ch, 0, 0);
  }

  /* ══ BACKGROUND FIELDS ══════════════════════════════════════════════════
     Every field is drawn on a coarser multiple of the mark grid (bgStep) so
     it stays aligned to the same lattice without costing a fillText per
     8px cell across the whole viewport. */
  bgSetup() {
    const R = this.rand || Math.random;
    const cfg = this.cfg;
    /* Coarseness is a look control, not a performance one — but at density 8
       on a wide display a step of 1 means tens of thousands of cells a frame.
       Raise the step until the field fits a fixed budget, so no combination of
       density, coarseness and viewport size can drop frames. */
    this.bgStep = Math.max(1, cfg.bgScale | 0);
    const BUDGET = 5200;
    const fits = s => (Math.ceil(this.gw / s) + 1) * (Math.ceil(this.gh / s) + 1);
    while (this.bgStep < 64 && fits(this.bgStep) > BUDGET) this.bgStep++;
    this.bw = Math.ceil(this.gw / this.bgStep) + 1;
    this.bh = Math.ceil(this.gh / this.bgStep) + 1;

    /* rain columns */
    this.rainCols = [];
    for (let i = 0; i < this.bw + 1; i++) {
      this.rainCols.push({
        y: R() * this.bh * 1.6 - this.bh * 0.3,
        v: 4 + R() * 16,
        len: 3 + (R() * 9) | 0,
        p: R()
      });
    }
    /* drifting motes for the flow field */
    this.motes = [];
    const n = Math.round(cfg.bgAmt * 520);
    for (let i = 0; i < n; i++)
      this.motes.push({ x: R() * this.bw, y: R() * this.bh, s: R(), life: R() });
    /* life board */
    const cells = this.bw * this.bh;
    this.life = new Uint8Array(cells);
    this.life2 = new Uint8Array(cells);
    for (let i = 0; i < cells; i++) this.life[i] = R() < 0.32 ? 1 : 0;
    this.lifeAcc = 0;
  }
  bgx(bx) { return this.ox + (this.gx0 + bx * this.bgStep + 0.5) * this.cell; }
  bgy(by) { return this.oy + (this.gy0 + by * this.bgStep + 0.5) * this.cell; }

  /* v is 0..1 intensity; the colour modes let the field read as part of the
     logo palette, as one fixed hue, or as a hue that maps across the field */
  bgInk(v, bx, by, hueShift) {
    const cfg = this.cfg;
    let h = 0, s = this.pal.sat, l = 32 + v * 54;
    switch (cfg.bgColor) {
      case 'mono':  s = 0; l = 24 + v * 70; break;
      case 'fixed': h = cfg.bgHue + hueShift; break;
      case 'sweep': h = cfg.bgHue + hueShift + v * 170; break;
      case 'space': h = cfg.bgHue + hueShift + bx * 6 + by * 9; break;
      case 'noise': h = this.pal.hue(() => h2(bx * 37 + by, 77)) + hueShift; break;
      /* feeding the intensity in as the palette's "random" draw keeps the field
         inside the logo palette while still letting its shape read */
      default:      h = this.pal.hue(() => v) + hueShift; break;
    }
    return 'hsl(' + (((h % 360) + 360) % 360) + ',' + s + '%,' + l + '%)';
  }

  drawBackground(t, dt, hueShift) {
    const cfg = this.cfg;
    if (cfg.bg === 'none' || cfg.bgAmt <= 0) return;
    /* the field recedes as the mark ignites, unless it is meant to live on */
    const fade = cfg.bgPersist ? 1 : 1 - clamp01((t - cfg.tConv) / 0.22);
    if (fade <= 0.004) return;
    const F = this['bg_' + cfg.bg];
    if (F) F.call(this, t, dt * cfg.bgSpeed, hueShift, fade * cfg.bgAmt);
  }

  bg_rain(t, dt, hueShift, amt) {
    const chars = this.chars;
    for (let i = 0; i < this.rainCols.length; i++) {
      const c = this.rainCols[i];
      if (c.p > this.cfg.bgAmt) continue;
      c.y += c.v * dt;
      if (c.y - c.len > this.bh) c.y = -(this.rand() * 20);
      const head = Math.round(c.y);
      for (let k = 0; k < c.len; k++) {
        const by = head - k;
        if (by < 0 || by > this.bh) continue;
        const a = (1 - k / c.len) * amt;
        if (a < 0.012) continue;
        const ch = chars[(h2(i * 97 + by, this.tick + k) * chars.length) | 0];
        this.glyph(ch, this.bgx(i), this.bgy(by),
          k === 0 ? '#fff' : this.bgInk(1 - k / c.len, i, by, hueShift), a);
      }
    }
  }

  bg_plasma(t, dt, hueShift, amt) {
    const ramp = this.ramp, n = ramp.length - 1;
    const T = t * this.cfg.bgSpeed * 1.4, k = 0.9 / this.cfg.bgScale;
    for (let by = 0; by < this.bh; by++) for (let bx = 0; bx < this.bw; bx++) {
      const v = (Math.sin(bx * k + T) + Math.sin(by * k * 1.6 - T * 1.2)
               + Math.sin((bx + by) * k * 0.7 + T * 0.8)
               + Math.sin(Math.hypot(bx - this.bw / 2, by - this.bh / 2) * k * 1.3 - T * 1.6)) / 4;
      const u = clamp01((v + 1) / 2);
      const u2 = u * u; const a = u2 * u2 * amt * 2.1;
      if (a < 0.035) continue;
      this.glyph(ramp[Math.min(n, (u * n) | 0)], this.bgx(bx), this.bgy(by),
        this.bgInk(u, bx, by, hueShift), a);
    }
  }

  bg_tunnel(t, dt, hueShift, amt) {
    const ramp = this.ramp, n = ramp.length - 1;
    const T = t * this.cfg.bgSpeed;
    const cx = this.bw / 2, cy = this.bh / 2;
    const spokes = 6 + this.cfg.bgScale * 2;
    for (let by = 0; by < this.bh; by++) for (let bx = 0; bx < this.bw; bx++) {
      const dx = bx - cx, dy = (by - cy) * 1.15;
      const r = Math.hypot(dx, dy);
      if (r < 0.7) continue;
      const ang = Math.atan2(dy, dx);
      const depth = 9 / r + T * 1.7;                    /* rushing inward */
      const twist = ang * spokes / (Math.PI * 2) + T * 0.35;
      const v = (Math.sin(depth * Math.PI * 2) * 0.6 + Math.sin(twist * Math.PI * 2) * 0.4);
      const u = clamp01((v + 1) / 2) * clamp01(r / 6);   /* dark eye at centre */
      const a = u * u * u * amt * 2.4;
      if (a < 0.035) continue;
      this.glyph(ramp[Math.min(n, (u * n) | 0)], this.bgx(bx), this.bgy(by),
        this.bgInk(u, bx, by, hueShift), a);
    }
  }

  bg_ripple(t, dt, hueShift, amt) {
    const ramp = this.ramp, n = ramp.length - 1;
    const T = t * this.cfg.bgSpeed;
    const k = 1.5 / this.cfg.bgScale;
    /* three slowly orbiting sources interfering */
    const src = [
      [this.bw * (0.5 + 0.34 * Math.cos(T * 0.5)), this.bh * (0.5 + 0.3 * Math.sin(T * 0.42))],
      [this.bw * (0.5 + 0.36 * Math.cos(T * -0.33 + 2)), this.bh * (0.5 + 0.32 * Math.sin(T * 0.55 + 1))],
      [this.bw * (0.5 + 0.3 * Math.cos(T * 0.61 + 4)), this.bh * (0.5 + 0.28 * Math.sin(T * -0.47 + 3))]
    ];
    for (let by = 0; by < this.bh; by++) for (let bx = 0; bx < this.bw; bx++) {
      let v = 0;
      for (let s = 0; s < 3; s++) {
        const d = Math.hypot(bx - src[s][0], (by - src[s][1]) * 1.15);
        v += Math.sin(d * k - T * 3.4) / (1 + d * 0.09);
      }
      const u = clamp01((v + 1.1) / 2.2);
      const a = u * u * u * amt * 2.4;
      if (a < 0.035) continue;
      this.glyph(ramp[Math.min(n, (u * n) | 0)], this.bgx(bx), this.bgy(by),
        this.bgInk(u, bx, by, hueShift), a);
    }
  }

  bg_flow(t, dt, hueShift, amt) {
    const chars = this.chars;
    const T = t * this.cfg.bgSpeed * 0.35, k = 0.5 / this.cfg.bgScale;
    for (let i = 0; i < this.motes.length; i++) {
      const m = this.motes[i];
      /* cheap curl-ish field: the gradient of two crossed sine sheets */
      const ang = Math.sin(m.x * k + T) * 2 + Math.cos(m.y * k * 1.3 - T * 0.8) * 2 + m.s * 0.7;
      const sp = (2.4 + m.s * 5) * dt * 2.2;
      m.x += Math.cos(ang) * sp;
      m.y += Math.sin(ang) * sp;
      m.life -= dt * 0.28;
      if (m.life <= 0 || m.x < -2 || m.x > this.bw + 2 || m.y < -2 || m.y > this.bh + 2) {
        m.x = this.rand() * this.bw; m.y = this.rand() * this.bh;
        m.life = 0.6 + this.rand() * 0.6; m.s = this.rand();
      }
      const bx = Math.round(m.x), by = Math.round(m.y);
      if (bx < 0 || bx > this.bw || by < 0 || by > this.bh) continue;
      const a = Math.min(1, m.life * 1.6) * amt * 1.5;
      if (a < 0.03) continue;
      this.glyph(chars[(h2(i, this.tick) * chars.length) | 0], this.bgx(bx), this.bgy(by),
        this.bgInk(m.s, bx, by, hueShift), a);
    }
  }

  bg_life(t, dt, hueShift, amt) {
    const chars = this.chars, W = this.bw, H = this.bh;
    this.lifeAcc += dt * (2 + this.cfg.bgSpeed * 7);
    if (this.lifeAcc >= 1) {
      this.lifeAcc = 0;
      const a = this.life, b = this.life2;
      let alive = 0;
      for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
        let k = 0;
        for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) {
          if (!dx && !dy) continue;
          k += a[((y + dy + H) % H) * W + ((x + dx + W) % W)];
        }
        const i = y * W + x;
        b[i] = a[i] ? (k === 2 || k === 3 ? 1 : 0) : (k === 3 ? 1 : 0);
        alive += b[i];
      }
      this.life = b; this.life2 = a;
      /* keep sprinkling, so the board never settles into a still life */
      const seed = Math.max(6, (W * H * 0.004) | 0);
      for (let i = 0; i < seed; i++)
        this.life[((this.rand() * H) | 0) * W + ((this.rand() * W) | 0)] = 1;
      if (alive < W * H * 0.02)
        for (let i = 0; i < W * H * 0.14; i++)
          this.life[((this.rand() * H) | 0) * W + ((this.rand() * W) | 0)] = 1;
    }
    const L = this.life;
    for (let by = 0; by < H; by++) for (let bx = 0; bx < W; bx++) {
      if (!L[by * W + bx]) continue;
      this.glyph(chars[(h2(bx * 41 + by, this.tick) * chars.length) | 0],
        this.bgx(bx), this.bgy(by), this.bgInk(0.8, bx, by, hueShift), amt);
    }
  }

  bg_static(t, dt, hueShift, amt) {
    const chars = this.chars, W = this.bw, H = this.bh;
    const tk = this.tick + Math.floor(t * this.cfg.bgSpeed * 26);
    const roll = (t * this.cfg.bgSpeed * 14) % (H + 10);
    for (let by = 0; by < H; by++) {
      /* torn bands slide sideways; a rolling bar brightens as it passes */
      const band = h2(by * 7, Math.floor(tk / 5));
      const shift = band < 0.22 ? Math.round((h2(by, tk) * 2 - 1) * W * 0.4) : 0;
      const near = Math.abs(by - roll);
      const boost = near < 4 ? (1 - near / 4) * 1.5 : 0;
      for (let bx = 0; bx < W; bx++) {
        const n = h2(bx * 131 + by * 17, tk);
        const a = (n * n * 0.9 + boost * n) * amt;
        if (a < 0.035) continue;
        this.glyph(chars[(n * chars.length) | 0],
          this.bgx((bx + shift + W) % W), this.bgy(by),
          this.bgInk(n, bx, by, hueShift), Math.min(1, a));
      }
    }
  }

  /* ── SHAFT — tunnel, but the rings are the mark's own rectangle, and the
     whole sampling frame rotates so the corners sweep past you ── */
  bg_shaft(t, dt, hueShift, amt) {
    const ramp = this.ramp, n = ramp.length - 1;
    const T = t * this.cfg.bgSpeed;
    const cx = this.bw / 2, cy = this.bh / 2;
    const rot = T * 0.22, ca = Math.cos(rot), sa = Math.sin(rot);
    const depthK = 9 + this.cfg.bgScale * 2;
    for (let by = 0; by < this.bh; by++) for (let bx = 0; bx < this.bw; bx++) {
      const dx = bx - cx, dy = (by - cy) * 1.1;
      const rx = dx * ca - dy * sa, ry = dx * sa + dy * ca;
      const r = rectR(rx, ry);
      if (r < 0.8) continue;
      const fall = r < 5 ? r / 5 : 1;          /* cheap reject before the trig */
      if (fall * amt < 0.02) continue;
      const depth = depthK / r + T * 1.8;
      /* 1 along the diagonals where the rectangle turns a corner */
      const corner = 1 - Math.min(1, Math.abs(Math.abs(rx) / RECT_AX - Math.abs(ry)) / r);
      const v = Math.sin(depth * Math.PI * 2) * 0.7
              + corner * 0.55 * Math.sin(depth * Math.PI * 2 + 1.3);
      const u = clamp01((v + 1) / 2) * fall;
      const a = u * u * u * amt * 2.4;
      if (a < 0.035) continue;
      this.glyph(ramp[Math.min(n, (u * n) | 0)], this.bgx(bx), this.bgy(by),
        this.bgInk(u, bx, by, hueShift), a);
    }
  }

  /* ── NEST — the logo silhouette repeated at nested scales, each ring
     growing continuously outward as a new one is born at the centre. An
     endless zoom into the mark. ── */
  bg_nest(t, dt, hueShift, amt) {
    const T = t * this.cfg.bgSpeed * 0.18;
    const growth = 1.75;
    const phase = T - Math.floor(T);            /* 0..1, drives the whole stack */
    const cx = this.bw / 2, cy = this.bh / 2;
    const outer = Math.max(this.bw, this.bh);
    const self = this;
    for (let k = 0; k < 7; k++) {
      const ms = 0.55 * Math.pow(growth, k + phase);
      if (ms * MARK_H < 2) continue;
      if (ms * MARK_H > outer * 2.4) break;
      /* fade in at the centre, out as it leaves the viewport */
      const span = clamp01((ms * MARK_H) / 4) * (1 - clamp01((ms * MARK_H) / (outer * 1.9)));
      const a = span * amt * 1.15;
      if (a < 0.03) continue;
      const u = 0.35 + 0.5 * (1 - k / 7);
      eachMarkEdge(cx - MARK_W * ms / 2, cy - MARK_H * ms / 2, ms, 1,
        function (x, y) {
          if (x < 0 || x > self.bw || y < 0 || y > self.bh) return;
          self.glyph(self.chars[(h2(x * 31 + y, self.tick) * self.chars.length) | 0],
            self.bgx(x), self.bgy(y), self.bgInk(u, x, y, hueShift), a);
        });
    }
  }

  /* ── MOIRE — two rectangular lattices at the mark's aspect, one slowly
     rotating against the other. Bright only where their lines coincide. ── */
  bg_moire(t, dt, hueShift, amt) {
    const ramp = this.ramp, n = ramp.length - 1;
    const T = t * this.cfg.bgSpeed;
    const cx = this.bw / 2, cy = this.bh / 2;
    const s1 = this.cfg.bgScale * 1.6 + Math.sin(T * 0.27) * 0.5;
    const s2 = s1 * (1.13 + Math.sin(T * 0.19) * 0.07);
    const rot = T * 0.05, ca = Math.cos(rot), sa = Math.sin(rot);
    const line = (p, s) => 1 - Math.abs((((p / s) % 1) + 1.5) % 1 - 0.5) * 2;
    for (let by = 0; by < this.bh; by++) for (let bx = 0; bx < this.bw; bx++) {
      const dx = bx - cx, dy = by - cy;
      const g1 = Math.max(line(dx, s1 * RECT_AX), line(dy, s1));
      const rx = dx * ca - dy * sa, ry = dx * sa + dy * ca;
      const g2 = Math.max(line(rx, s2 * RECT_AX), line(ry, s2));
      const u = clamp01(g1 * g2);
      const u2 = u * u; const a = u2 * u2 * amt * 2.6;
      if (a < 0.035) continue;
      this.glyph(ramp[Math.min(n, (u * n) | 0)], this.bgx(bx), this.bgy(by),
        this.bgInk(u, bx, by, hueShift), a);
    }
  }

  /* ── CIRCUIT — orthogonal buses with packets running along them. The mark
     is a boxed glyph; this is the board it sits on. ── */
  bg_circuit(t, dt, hueShift, amt) {
    const T = t * this.cfg.bgSpeed;
    const dens = 0.1 + this.cfg.bgAmt * 0.22;
    const W = this.bw, H = this.bh;
    for (let by = 0; by < H; by++) {
      const hBus = h2(by * 17, 3) < dens;
      for (let bx = 0; bx < W; bx++) {
        const vBus = h2(bx * 23, 7) < dens;
        if (!hBus && !vBus) continue;
        let u = 0.3, ch;
        if (hBus && vBus) ch = WIRE[2];
        else if (hBus) ch = WIRE[0];
        else ch = WIRE[1];
        /* a packet slides along each bus; brightness peaks as it passes */
        if (hBus) {
          const sp = 4 + h2(by, 11) * 14, dir = h2(by, 13) < 0.5 ? 1 : -1;
          const head = (((T * sp * dir) % W) + W) % W;
          const d = Math.min(Math.abs(bx - head), W - Math.abs(bx - head));
          if (d < 5) u = Math.max(u, 1 - d / 5);
        }
        if (vBus) {
          const sp = 4 + h2(bx, 19) * 14, dir = h2(bx, 29) < 0.5 ? 1 : -1;
          const head = (((T * sp * dir) % H) + H) % H;
          const d = Math.min(Math.abs(by - head), H - Math.abs(by - head));
          if (d < 5) u = Math.max(u, 1 - d / 5);
        }
        const a = u * amt * 1.9;
        if (a < 0.03) continue;
        if (u > 0.62) ch = SOLID;
        this.glyph(ch, this.bgx(bx), this.bgy(by),
          this.bgInk(u, bx, by, hueShift), Math.min(1, a));
      }
    }
  }

  /* ── LABYRINTH — the mark reads as a maze glyph, so the ground behind it is
     one too. Walls are drawn as real runs along a lattice and joined with the
     proper box-drawing junctions; scattering random glyphs per cell just makes
     speckle, not a maze. A seam of light wanders through it. ── */
  bg_maze(t, dt, hueShift, amt) {
    const cfg = this.cfg;
    const T = t * cfg.bgSpeed;
    const L = 3 + (cfg.bgScale % 4);              /* lattice spacing, in cells */
    const gen = Math.floor(T * 0.5);
    const p = 0.3 + cfg.bgAmt * 0.36;
    const W = this.bw, H = this.bh, self = this;
    const cols = Math.ceil(W / L) + 1, rows = Math.ceil(H / L) + 1;
    const seam = (T * 7) % (W + H + 20) - 10;
    function put(bx, by, ch) {
      if (bx < 0 || bx > W || by < 0 || by > H) return;
      const d = Math.abs(bx + by - seam);
      const lit = d < 9 ? 1 - d / 9 : 0;
      /* box-drawing glyphs are thin strokes — they carry a fraction of the ink
         a '#' does, so they need more alpha to read at the same weight */
      const a = (0.9 + lit * 0.1) * amt;
      if (a < 0.03) return;
      self.glyph(lit > 0.82 ? SOLID : ch, self.bgx(bx), self.bgy(by),
        self.bgInk(0.58 + lit * 0.42, bx, by, hueShift), Math.min(1, a));
    }
    const wallR = (i, j) => h2(i * 31 + j * 7, gen) < p;
    const wallD = (i, j) => h2(i * 31 + j * 7, gen + 977) < p;
    for (let j = 0; j < rows; j++) for (let i = 0; i < cols; i++) {
      const x0 = i * L, y0 = j * L;
      const r = wallR(i, j), d = wallD(i, j);
      if (r) for (let k = 1; k < L; k++) put(x0 + k, y0, '─');
      if (d) for (let k = 1; k < L; k++) put(x0, y0 + k, '│');
      const n = (r ? 1 : 0) | (d ? 2 : 0)
              | (j > 0 && wallD(i, j - 1) ? 4 : 0)
              | (i > 0 && wallR(i - 1, j) ? 8 : 0);
      if (n) put(x0, y0, NODE[n]);
    }
  }

  /* ══ PULSE ══════════════════════════════════════════════════════════════
     Fired the moment the mark completes. Everything here is built from the
     mark's own rectangle (and, for `echo`, its actual silhouette) so the
     shape that leaves the logo matches the shape of the logo. */
  pulseCell(gx, gy, a, hueShift, v) {
    if (gx < this.gx0 || gx > this.gx1 || gy < this.gy0 || gy > this.gy1) return;
    const cfg = this.cfg;
    let col;
    if (cfg.pulseColor === 'mono') col = 'hsl(0,0%,' + (70 + v * 30) + '%)';
    else if (cfg.pulseColor === 'fixed') col = 'hsl(' + (((cfg.pulseHue + hueShift) % 360 + 360) % 360) + ',100%,' + (58 + v * 34) + '%)';
    else if (cfg.pulseColor === 'space') col = 'hsl(' + (((cfg.pulseHue + hueShift + gx * 5 + gy * 7) % 360 + 360) % 360) + ',100%,62%)';
    else col = 'hsl(' + (((this.pal.hue(() => h2(gx * 13 + gy, 5)) + hueShift) % 360 + 360) % 360) + ',' + this.pal.sat + '%,' + (58 + v * 34) + '%)';
    this.glyph(this.chars[(h2(gx * 13 + gy, this.tick) * this.chars.length) | 0],
      this.px(gx), this.py(gy), col, a);
  }
  /* one rectangle outline, `th` cells thick, drawn on the grid */
  pulseRect(hw, hh, th, a, hueShift, v) {
    const x0 = Math.round(this.mcx - hw), x1 = Math.round(this.mcx + hw);
    const y0 = Math.round(this.mcy - hh), y1 = Math.round(this.mcy + hh);
    for (let k = 0; k < th; k++) {
      for (let x = x0 - k; x <= x1 + k; x++) {
        this.pulseCell(x, y0 - k, a, hueShift, v);
        this.pulseCell(x, y1 + k, a, hueShift, v);
      }
      for (let y = y0 - k + 1; y <= y1 + k - 1; y++) {
        this.pulseCell(x0 - k, y, a, hueShift, v);
        this.pulseCell(x1 + k, y, a, hueShift, v);
      }
    }
  }

  drawPulse(t, hueShift) {
    const cfg = this.cfg;
    if (cfg.pulse === 'none') return;
    const span = 0.16 + cfg.pulseReach * 0.5;
    const w0 = (t - cfg.tConv) / span;
    if (w0 <= 0) return;
    const F = this['pulse_' + cfg.pulse];
    if (!F) return;
    const echoes = cfg.pulseEchoes;
    for (let e = 0; e < echoes; e++) {
      const w = w0 - e * (0.72 / echoes);
      if (w <= 0 || w >= 1) continue;
      const a = (1 - w) * (1 - w) * cfg.pulseAmt * (e ? 0.55 / Math.sqrt(e + 1) : 1);
      if (a < 0.012) continue;
      F.call(this, w, a, hueShift);
    }
  }

  /* the mark's own rectangle, expanding — matches the logo's 11:9 */
  pulse_rect(w, a, hueShift) {
    const S = this.cfg.density, reach = this.gw * 0.5 * this.cfg.pulseReach;
    const g = eOutCubic(w) * reach;
    this.pulseRect(MARK_W * S / 2 + g, MARK_H * S / 2 + g * 9 / 11,
      this.cfg.pulseThick, a, hueShift, 1 - w);
  }
  /* The actual logo silhouette, ghosting outward. Scaling the mark's cells
     apart would just spread them into scattered dots, so this re-walks the
     11x9 module pattern at the echo's scale and emits only the edges that
     border empty space — a true outline of the logo at any size. */
  pulse_echo(w, a, hueShift) {
    const S = this.cfg.density;
    const f = 1 + eOutCubic(w) * (0.5 + this.cfg.pulseReach * 2.2);
    const ms = S * f;                          /* cells per module at this scale */
    const th = Math.max(1, Math.round(this.cfg.pulseThick / Math.sqrt(f)));
    const v = 1 - w, self = this;
    eachMarkEdge(this.mcx - MARK_W * ms / 2, this.mcy - MARK_H * ms / 2, ms, th,
      function (x, y) { self.pulseCell(x, y, a, hueShift, v); });
  }

  /* four beams along the mark's own axes */
  pulse_cross(w, a, hueShift) {
    const S = this.cfg.density;
    const e = eOutCubic(w), reach = this.gw * 0.55 * this.cfg.pulseReach;
    const hw = MARK_W * S / 2, hh = MARK_H * S / 2;
    const len = e * reach, th = this.cfg.pulseThick;
    for (let k = -Math.floor(th / 2); k <= Math.floor(th / 2); k++) {
      for (let d = 0; d < len; d++) {
        const f = 1 - d / (len || 1);
        this.pulseCell(Math.round(this.mcx + hw + d), Math.round(this.mcy + k), a * f, hueShift, f);
        this.pulseCell(Math.round(this.mcx - hw - d), Math.round(this.mcy + k), a * f, hueShift, f);
        this.pulseCell(Math.round(this.mcx + k), Math.round(this.mcy + hh + d * 0.82), a * f, hueShift, f);
        this.pulseCell(Math.round(this.mcx + k), Math.round(this.mcy - hh - d * 0.82), a * f, hueShift, f);
      }
    }
  }
  /* four L-brackets leaving the corners */
  pulse_corners(w, a, hueShift) {
    const S = this.cfg.density;
    const e = eOutCubic(w), g = e * this.gw * 0.42 * this.cfg.pulseReach;
    const hw = MARK_W * S / 2 + g, hh = MARK_H * S / 2 + g * 9 / 11;
    const arm = Math.max(2, Math.round((MARK_W * S) * (0.3 + 0.5 * (1 - w))));
    const th = this.cfg.pulseThick;
    for (const sx of [-1, 1]) for (const sy of [-1, 1]) {
      const cx = Math.round(this.mcx + sx * hw), cy = Math.round(this.mcy + sy * hh);
      for (let k = 0; k < th; k++) for (let d = 0; d < arm; d++) {
        const f = 1 - d / arm;
        this.pulseCell(cx - sx * d, cy + sy * k, a * f, hueShift, f);
        this.pulseCell(cx + sx * k, cy - sy * d, a * f, hueShift, f);
      }
    }
  }
  /* two full-width bars sliding off the top and bottom of the mark */
  pulse_scan(w, a, hueShift) {
    const S = this.cfg.density;
    const e = eOutCubic(w), g = e * this.gh * 0.6 * this.cfg.pulseReach;
    const hh = MARK_H * S / 2 + g;
    const half = Math.round(MARK_W * S * (0.5 + e * 1.6));
    const th = this.cfg.pulseThick;
    for (let k = 0; k < th; k++)
      for (let x = -half; x <= half; x++) {
        const f = 1 - Math.abs(x) / (half || 1);
        this.pulseCell(Math.round(this.mcx + x), Math.round(this.mcy - hh - k), a * f, hueShift, f);
        this.pulseCell(Math.round(this.mcx + x), Math.round(this.mcy + hh + k), a * f, hueShift, f);
      }
  }
  /* the original circular shockwave, kept as an option */
  pulse_circle(w, a, hueShift) {
    const rr = eOutCubic(w) * Math.hypot(this.gw, this.gh) * 0.62 * this.cfg.pulseReach * 2;
    const steps = Math.max(28, Math.round(rr * 6.5));
    for (let k = 0; k < this.cfg.pulseThick; k++)
      for (let i = 0; i < steps; i++) {
        const ang = i / steps * Math.PI * 2;
        this.pulseCell(Math.round(this.mcx + Math.cos(ang) * (rr + k)),
          Math.round(this.mcy + Math.sin(ang) * (rr + k) * 0.92), a, hueShift, 1 - w);
      }
  }

  step(now) {
    if (!this.running || !this.cfg) return;
    /* a hidden tab or a collapsed container reports a 0x0 viewport, which
       makes the buffers unusable — idle until there is something to draw on */
    if (this.oc.width < 2 || this.oc.height < 2) {
      this.layout();
      if (this.oc.width < 2 || this.oc.height < 2) {
        this.raf = requestAnimationFrame(this.step);
        return;
      }
    }
    const cfg = this.cfg;
    const el = (now - this.t0) / 1000;
    let dt = (now - this.last) / 1000; this.last = now;
    if (dt > 0.1) dt = 0.1;
    if (this.frames++ < 8) this.reanchor();
    const t = (now - this.t0) / cfg.durMs;
    this.tick = Math.floor(el * (2 + cfg.churn));
    this.cfg.churnRate = (2 + cfg.churn) / 60;

    const o = this.octx, c = this.ctx, d = this.dpr;
    o.setTransform(1, 0, 0, 1, 0, 0);
    o.globalCompositeOperation = 'source-over';
    o.globalAlpha = 1;
    o.clearRect(0, 0, this.oc.width, this.oc.height);
    o.font = this.font; o.textAlign = 'center'; o.textBaseline = 'middle';

    const hueShift = cfg.drift * el;
    const tc = clamp01(t / cfg.tConv);
    /* global ignite progress, and how much of its window is spent staggering */
    const gIg = cfg.solidify ? clamp01((t - cfg.tConv) / (T_IGN - cfg.tConv)) : 0;
    const SG = cfg.igniteStyle === 'flash' ? 0 : 0.72;
    const phKey = cfg.igniteStyle === 'wave' ? 'phWave'
                : cfg.igniteStyle === 'scan' ? 'phScan'
                : cfg.igniteStyle === 'bloom' ? 'phRand' : null;
    const markFade = 1 - clamp01((t - T_IGN) / 0.06);
    if (cfg.onIgnite) cfg.onIgnite(gIg, markFade);
    const done = t >= 1.02;
    const out = this.out || (this.out = [0, 0]);
    const chars = this.chars, nch = chars.length;
    const ramp = this.ramp, nramp = ramp.length;
    const splitPx = cfg.split * this.cell * 0.45;
    const half = this.cell / 2;

    this.drawBackground(t, dt, hueShift);

    for (let i = 0; done ? false : i < this.parts.length; i++) {
      const p = this.parts[i];
      if (tc < p.delay) continue;
      const q = clamp01((tc - p.delay) / p.dur);

      let a;
      if (p.kind === 0) {                       /* loose chars — bloom and vanish */
        a = Math.sin(clamp01(q * 1.7) * Math.PI) * 0.5;
        if (a <= 0.02) continue;
      } else {
        a = markFade;
        if (a <= 0.01) continue;
      }

      this.pos(p, q, el, out);
      const gx = Math.round(out[0]), gy = Math.round(out[1]);
      if (gx < this.gx0 || gx > this.gx1 || gy < this.gy0 || gy > this.gy1) continue;

      /* IGNITE — instead of snapping to a block, each landed cell climbs the
         density ramp and glows, so the gaps between characters close and the
         mark swells into a solid shape with nothing ever popping in. */
      let ig = 0;
      if (p.kind === 1 && gIg > 0 && q >= 1) {
        ig = phKey === null ? gIg
           : clamp01((gIg - p[phKey] * SG) / (1 - SG));
      }

      let ch;
      if (ig > 0) ch = ramp[Math.min(nramp - 1, (ig * nramp) | 0)];
      else if (q >= 0.97) ch = p.fch;
      else ch = chars[(h2(p.seed, this.tick) * nch) | 0];

      const e = smooth(q);
      const hue = (p.hue + hueShift + (1 - e) * p.spin * 120) % 360;
      const col = 'hsl(' + hue + ',' + (p.sat * (1 - e)) + '%,' + (46 + 54 * e) + '%)';
      const x = this.px(gx), y = this.py(gy);

      /* the last of the ignite lays a solid cell down, so glyph side-bearings
         can never leave hairline seams in the finished mark */
      if (ig > 0.9) {
        o.globalAlpha = clamp01((ig - 0.9) / 0.1) * a;
        o.fillStyle = '#fff';
        o.setTransform(d, 0, 0, d, 0, 0);
        o.fillRect(x - half, y - half, this.cell + 0.6, this.cell + 0.6);
      }

      if (splitPx > 0.2 && e < 0.98) {
        const s = splitPx * (1 - e);
        o.globalCompositeOperation = 'lighter';
        this.glyph(ch, x - s, y, '#ff0044', a * 0.55);
        this.glyph(ch, x + s, y, '#00ffee', a * 0.55);
        o.globalCompositeOperation = 'source-over';
      }
      this.glyph(ch, x, y, col, a);
    }

    if (!done) this.drawPulse(t, hueShift);

    /* compose: fading trail buffer + this frame + bloom */
    c.setTransform(1, 0, 0, 1, 0, 0);
    c.globalCompositeOperation = 'source-over';
    c.globalAlpha = 1;
    c.filter = 'none';
    if (cfg.trails > 0) {
      c.fillStyle = 'rgba(0,0,0,' + (1 - cfg.trails) + ')';
      c.fillRect(0, 0, this.cv.width, this.cv.height);
    } else {
      c.clearRect(0, 0, this.cv.width, this.cv.height);
    }
    c.globalCompositeOperation = 'lighter';
    c.drawImage(this.oc, 0, 0);
    const glow = cfg.bloom + cfg.afterglow * Math.sin(gIg * Math.PI) * markFade;
    if (glow > 0.01) {
      c.globalAlpha = Math.min(1, glow);
      c.filter = 'blur(' + (this.cell * (0.6 + 1.8 * gIg * markFade)).toFixed(1) + 'px)';
      c.drawImage(this.oc, 0, 0);
      c.filter = 'none';
      c.globalAlpha = 1;
    }
    c.globalCompositeOperation = 'source-over';

    if (t < 1.02 || cfg.bgPersist) this.raf = requestAnimationFrame(this.step);
    else this.halt();
  }
}

/* ═══════════════════════════════════════════════════════════════════════
   Button ascii effects — each button owns a small character field that
   reacts to the pointer, plus a label that can decode / tear / glitch.
   ═══════════════════════════════════════════════════════════════════════ */
class ButtonFx {
  constructor(btn) {
    this.btn = btn;
    this.cv = btn.querySelector('.btn-canvas');
    this.ctx = this.cv.getContext('2d');
    this.lbl = btn.querySelector('.label');
    this.glyphs = btn.querySelector('.lbl-glyphs');
    this.text = (this.lbl && this.lbl.getAttribute('data-text')) || '';
    /* setLabel builds one span per character; leaving the original text node in
       place would render the word twice over */
    if (this.glyphs) this.glyphs.textContent = '';
    this.hover = 0; this.want = 0; this.pulse = 0; this.scram = 0;
    this.wipeDir = 1; this.wipeAmt = -1; this.hotAll = false; this.charX = [];
    this.mx = 0.5; this.my = 0.5;
    this.t = 0; this.w = 0; this.h = 0;
    this.cols = 0; this.rows = 0;
    this.seed = (Math.random() * 1e6) | 0;

    btn.addEventListener('pointerenter', e => {
      this.want = 1; this.scram = 1;
      /* wipe away from the edge the pointer came in on */
      const r = btn.getBoundingClientRect();
      this.wipeDir = (e.clientX - r.left) < r.width / 2 ? 1 : -1;
    });
    btn.addEventListener('pointerleave', () => { this.want = 0; this.scram = 0.75; this.mx = .5; this.my = .5; });
    btn.addEventListener('pointermove', e => {
      const r = btn.getBoundingClientRect();
      this.mx = (e.clientX - r.left) / (r.width || 1);
      this.my = (e.clientY - r.top) / (r.height || 1);
    });
    if (window.ResizeObserver) {
      this.ro = new ResizeObserver(() => { this.dirty = true; });
      this.ro.observe(btn);
    }
  }
  destroy() { if (this.ro) this.ro.disconnect(); }

  layout() {
    const r = this.btn.getBoundingClientRect();
    if (!r.width || !r.height) return false;
    const dpr = this.dpr = Math.min(2, window.devicePixelRatio || 1);
    this.w = r.width; this.h = r.height;
    this.cv.width = Math.round(r.width * dpr);
    this.cv.height = Math.round(r.height * dpr);
    this.cell = Math.max(3, this.cfgCell || 7);
    this.cols = Math.ceil(r.width / this.cell) + 1;
    this.rows = Math.ceil(r.height / this.cell) + 1;
    const c = this.ctx;
    c.setTransform(1, 0, 0, 1, 0, 0);
    c.font = Math.round(this.cell * 1.14) + 'px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace';
    c.textAlign = 'center'; c.textBaseline = 'middle';
    this.xs = this.cell / (c.measureText(SOLID).width || this.cell * .6);
    this.charX = [];
    this.dirty = false;
    return true;
  }

  glyph(ch, x, y, color, alpha) {
    const c = this.ctx, d = this.dpr;
    c.globalAlpha = alpha; c.fillStyle = color;
    c.setTransform(d * this.xs, 0, 0, d, d * x, d * y);
    c.fillText(ch, 0, 0);
  }

  frame(dt, cfg) {
    if (this.cfgCell !== cfg.charPx) { this.cfgCell = cfg.charPx; this.dirty = true; }
    if (this.dirty || !this.cv.width) { if (!this.layout()) return; }
    const speed = cfg.speed;
    this.t += dt * speed;
    /* One value drives the whole button: fill on hover at `attack`, drain on
       leave at `release`. Hover used to borrow the intro's pulse, which kept
       heat pinned high for most of a second after the pointer left — the
       effect carried on playing and the colour flip arrived late. */
    const rate = this.want ? cfg.attack : cfg.release;
    this.hover += (this.want - this.hover) * Math.min(1, dt / Math.max(0.016, rate));
    if (!this.want && this.hover < 0.002) this.hover = 0;
    if (this.pulse > 0 && !this.want) this.pulse = Math.max(0, this.pulse - dt * 1.4);
    if (this.scram > 0) this.scram = Math.max(0, this.scram - dt * (0.85 + speed * 0.75));
    const heat = Math.max(this.hover, this.pulse);
    const idle = cfg.idle;
    const amp = (idle + (1 - idle) * heat) * cfg.intensity;

    /* A cross-faded invert goes through 50% grey, where a grey label on a grey
       ground is unreadable — so `snap` flips outright (hysteresis-gated) and
       `wipe` sweeps a hard edge across instead. Every pixel is always either
       black or white. */
    const mode = cfg.invert ? cfg.invertMode : 'none';
    if (mode === 'snap') {
      if (heat > 0.6) this.hot = true; else if (heat < 0.25) this.hot = false;
      this.wipeAmt = -1;
    } else if (mode === 'wipe') {
      this.hot = false;
      this.wipeAmt = heat > 0.001 ? heat : -1;
    } else {
      this.hot = false; this.wipeAmt = -1;
    }
    this.hotAll = !!this.hot;
    const hot = this.hotAll;
    this.btn.classList.toggle('fx-hot', hot);
    this.btn.classList.toggle('fx-mono', !!cfg.mono);

    const c = this.ctx;
    c.setTransform(1, 0, 0, 1, 0, 0);
    c.globalCompositeOperation = 'source-over';
    c.globalAlpha = 1;
    c.clearRect(0, 0, this.cv.width, this.cv.height);
    c.font = Math.round(this.cell * 1.14) + 'px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace';
    c.textAlign = 'center'; c.textBaseline = 'middle';

    if (this.wipeAmt > 0) {
      const w = this.w * Math.min(1, this.wipeAmt);
      c.setTransform(this.dpr, 0, 0, this.dpr, 0, 0);
      c.fillStyle = '#000';
      c.fillRect(this.wipeDir > 0 ? 0 : this.w - w, 0, w, this.h);
    }

    const F = this['fx_' + cfg.variant];
    if (F) F.call(this, amp, heat, hot, cfg);
    this.paintLabel();
    if (cfg.variant !== 'scramble' && cfg.variant !== 'glitch') this.setLabel(this.text);
  }

  /* black chars while the button is white, palette chars once it inverts */
  /* dark ink on the white ground, bright ink on the inverted one */
  hotAt(x) {
    if (this.wipeAmt < 0) return this.hotAll;
    const w = this.w * Math.min(1, this.wipeAmt);
    return this.wipeDir > 0 ? x < w : x > this.w - w;
  }
  ink(hue, sat, light, hot, x) {
    if (this.wipeAmt >= 0 && x !== undefined) hot = this.hotAt(x);
    return hot ? 'hsl(' + (hue % 360) + ',' + sat + '%,' + light + '%)'
               : 'hsl(' + (hue % 360) + ',' + Math.min(sat, 85) + '%,' + Math.max(4, light - 62) + '%)';
  }
  setLabel(s) {
    const g = this.glyphs;
    if (!g || this._label === s) return;
    this._label = s;
    while (g.children.length < s.length) g.appendChild(document.createElement('span'));
    while (g.children.length > s.length) g.removeChild(g.lastChild);
    for (let i = 0; i < s.length; i++) {
      const sp = g.children[i];
      if (sp.textContent !== s[i]) sp.textContent = s[i];
    }
    if (this.charX.length !== s.length) this.measureChars();
  }
  measureChars() {
    const g = this.glyphs; if (!g) return;
    const b = this.btn.getBoundingClientRect();
    this.charX = [...g.children].map(sp => {
      const r = sp.getBoundingClientRect();
      return r.left - b.left + r.width / 2;
    });
  }
  paintLabel() {
    const g = this.glyphs; if (!g) return;
    const n = g.children.length;
    if (this.charX.length !== n) this.measureChars();
    for (let i = 0; i < n; i++) {
      const on = this.wipeAmt >= 0 ? this.hotAt(this.charX[i] || 0) : this.hotAll;
      const col = on ? '#fff' : '#000';
      if (g.children[i]._c !== col) { g.children[i].style.color = col; g.children[i]._c = col; }
    }
  }

  fx_none() { this.setLabel(this.text); this.lbl.style.textShadow = ''; this.lbl.style.transform = ''; }

  fx_scramble(amp, heat, hot, cfg) {
    this.lbl.style.textShadow = ''; this.lbl.style.transform = '';
    const n = this.text.length;
    const p = 1 - clamp01(this.scram);
    const chars = CHARSETS[cfg.charset] || CHARSETS.blocks;
    const tick = Math.floor(this.t * 22);
    let s = '';
    for (let i = 0; i < n; i++) {
      const src = this.text[i];
      if (src === ' ') { s += ' '; continue; }
      const reveal = clamp01(p * (n + 4) - i);        /* resolves left to right */
      s += reveal >= 1 ? src : chars[(h2(this.seed + i, tick + i) * chars.length) | 0];
    }
    this.setLabel(s);
    /* faint field behind, so the button never looks empty */
    if (amp <= 0.02) return;
    for (let r = 0; r < this.rows; r++) for (let cx = 0; cx < this.cols; cx++) {
      if (h2(cx * 31 + r, this.seed) > 0.16 * amp + 0.02) continue;
      const ch = chars[(h2(cx + r * 7, tick) * chars.length) | 0];
      const gx0 = (cx + .5) * this.cell;
      this.glyph(ch, gx0, (r + .5) * this.cell,
        this.ink(this.t * 60 + cx * 12, 100, 62, hot, gx0), 0.45 * amp);
    }
  }

  fx_rain(amp, heat, hot, cfg) {
    this.lbl.style.textShadow = ''; this.lbl.style.transform = '';
    if (amp <= 0.01) return;
    const chars = CHARSETS[cfg.charset] || CHARSETS.blocks;
    const tick = Math.floor(this.t * 16);
    for (let cx = 0; cx < this.cols; cx++) {
      const v = 2.2 + h2(cx, this.seed) * 6;
      const len = 2 + ((h2(cx, this.seed + 3) * 4) | 0);
      const head = ((this.t * v + h2(cx, this.seed + 9) * this.rows * 3) % (this.rows + len + 3)) - len;
      for (let k = 0; k < len; k++) {
        const r = Math.floor(head) - k;
        if (r < 0 || r >= this.rows) continue;
        const a = (1 - k / len) * 0.95 * amp;
        const ch = chars[(h2(cx * 17 + r, tick + k) * chars.length) | 0];
        const gx1 = (cx + .5) * this.cell;
        this.glyph(ch, gx1, (r + .5) * this.cell,
          k === 0 ? (this.hotAt(gx1) ? '#fff' : '#000')
                  : this.ink(cx * 26 + this.t * 40, 100, 60, hot, gx1), a);
      }
    }
  }

  fx_plasma(amp, heat, hot, cfg) {
    this.lbl.style.textShadow = ''; this.lbl.style.transform = '';
    if (amp <= 0.01) return;
    const chars = CHARSETS[cfg.charset] || CHARSETS.blocks;
    const T = this.t * 1.6;
    const mcx = this.mx * this.cols, mcy = this.my * this.rows;
    for (let r = 0; r < this.rows; r++) for (let cx = 0; cx < this.cols; cx++) {
      let v = Math.sin(cx * .42 + T) + Math.sin(r * .7 - T * 1.3)
            + Math.sin((cx + r) * .3 + T * .7);
      const d = Math.hypot(cx - mcx, (r - mcy) * 1.6);
      v += Math.sin(d * .8 - T * 4) * 1.7 * heat / (1 + d * .18);   /* cursor ripple */
      const n = clamp01((v + 3.2) / 6.4);
      const a = Math.pow(n, 1.25) * amp;
      if (a < 0.03) continue;
      const ch = chars[Math.min(chars.length - 1, (n * chars.length) | 0)];
      const gx2 = (cx + .5) * this.cell;
      this.glyph(ch, gx2, (r + .5) * this.cell,
        this.ink(n * 220 + this.t * 55, 100, 48 + n * 42, hot, gx2), a);
    }
  }

  fx_glitch(amp, heat, hot, cfg) {
    const chars = CHARSETS[cfg.charset] || CHARSETS.blocks;
    const tick = Math.floor(this.t * 15);
    const k = amp;
    /* label: rgb split + jitter */
    const j = (h2(tick, this.seed) * 2 - 1) * 3 * k;
    const sp = (0.6 + h2(tick, this.seed + 1) * 2.6) * k;
    this.lbl.style.transform = 'translateX(' + j.toFixed(2) + 'px)';
    this.lbl.style.textShadow = sp > 0.1
      ? (-sp).toFixed(2) + 'px 0 rgba(255,0,80,.85),' + sp.toFixed(2) + 'px 0 rgba(0,240,255,.85)'
      : '';
    let s = this.text;
    if (k > 0.25 && h2(tick, this.seed + 5) < 0.35 * k) {
      s = s.split('').map((ch, i) =>
        h2(tick + i, this.seed) < 0.4 ? chars[(h2(i, tick) * chars.length) | 0] : ch).join('');
    }
    this.setLabel(s);
    if (amp <= 0.01) return;
    /* torn horizontal bands of characters */
    for (let r = 0; r < this.rows; r++) {
      if (h2(r * 13, tick) > 0.42 * k) continue;
      const off = (h2(r, tick + 2) * 2 - 1) * this.cols * 0.5;
      for (let cx = 0; cx < this.cols; cx++) {
        const ch = chars[(h2(cx + Math.round(off), tick + r) * chars.length) | 0];
        const gx3 = (cx + .5) * this.cell;
        this.glyph(ch, gx3, (r + .5) * this.cell,
          this.ink(r * 40 + tick * 17, 100, 60, hot, gx3), 0.55 * k);
      }
    }
  }

  /* characters stream sideways like a ticker, faster where the pointer is */
  fx_sweep(amp, heat, hot, cfg) {
    this.lbl.style.textShadow = ''; this.lbl.style.transform = '';
    if (amp <= 0.01) return;
    const chars = CHARSETS[cfg.charset] || CHARSETS.blocks;
    const tick = Math.floor(this.t * 18);
    for (let r = 0; r < this.rows; r++) {
      const dir = r % 2 ? 1 : -1;
      const off = this.t * (7 + r * 2.2) * dir;
      for (let cx = 0; cx < this.cols; cx++) {
        const src = Math.round(cx + off);
        const n = h2(src * 29 + r * 13, tick >> 3);
        if (n > 0.34 * amp + 0.04) continue;
        const x = (cx + .5) * this.cell;
        const near = 1 - Math.min(1, Math.abs(cx / this.cols - this.mx) * 3);
        this.glyph(chars[(n * chars.length) | 0], x, (r + .5) * this.cell,
          this.ink(r * 30 + this.t * 40, 100, 58, hot, x), (0.5 + near * 0.5) * amp);
      }
    }
  }

  /* a ring of characters chasing round the button's edge */
  fx_orbit(amp, heat, hot, cfg) {
    this.lbl.style.textShadow = ''; this.lbl.style.transform = '';
    if (amp <= 0.01) return;
    const chars = CHARSETS[cfg.charset] || CHARSETS.blocks;
    const per = (this.cols + this.rows) * 2;
    const head = (this.t * 26) % per;
    const tail = Math.max(4, Math.round(per * 0.3 * amp));
    for (let k = 0; k < tail; k++) {
      let i = (head - k + per * 2) % per;
      let cx, r;
      if (i < this.cols) { cx = i; r = 0; }
      else if (i < this.cols + this.rows) { cx = this.cols - 1; r = i - this.cols; }
      else if (i < this.cols * 2 + this.rows) { cx = this.cols * 2 + this.rows - 1 - i; r = this.rows - 1; }
      else { cx = 0; r = per - i; }
      const x = (cx + .5) * this.cell;
      const a = (1 - k / tail) * amp;
      this.glyph(chars[(h2(cx * 7 + r, Math.floor(this.t * 20)) * chars.length) | 0],
        x, (r + .5) * this.cell, this.ink(k * 12 + this.t * 60, 100, 62, hot, x), a);
    }
  }

  /* the field burns outward from wherever the pointer is */
  fx_ember(amp, heat, hot, cfg) {
    this.lbl.style.textShadow = ''; this.lbl.style.transform = '';
    if (amp <= 0.01) return;
    const chars = CHARSETS[cfg.charset] || CHARSETS.blocks;
    const tick = Math.floor(this.t * 20);
    const mcx = this.mx * this.cols, mcy = this.my * this.rows;
    const reach = (0.35 + heat * 1.1) * Math.max(this.cols, this.rows);
    for (let r = 0; r < this.rows; r++) for (let cx = 0; cx < this.cols; cx++) {
      const d = Math.hypot(cx - mcx, (r - mcy) * 1.7);
      const f = 1 - Math.min(1, d / reach);
      if (f <= 0.02) continue;
      const n = h2(cx * 53 + r * 11, tick + ((d * 2) | 0));
      if (n > f * 0.85) continue;
      const x = (cx + .5) * this.cell;
      this.glyph(chars[Math.min(chars.length - 1, (f * chars.length) | 0)],
        x, (r + .5) * this.cell,
        this.ink(30 + f * 45 + this.t * 20, 100, 45 + f * 40, hot, x), f * amp);
    }
  }

  fx_dissolve(amp, heat, hot, cfg) {
    this.lbl.style.textShadow = ''; this.lbl.style.transform = '';
    if (amp <= 0.01) return;
    const chars = CHARSETS[cfg.charset] || CHARSETS.blocks;
    const tick = Math.floor(this.t * 14);
    /* coverage grows in from the edges as the button heats up */
    for (let r = 0; r < this.rows; r++) for (let cx = 0; cx < this.cols; cx++) {
      const ex = Math.min(cx, this.cols - 1 - cx) / (this.cols / 2);
      const ey = Math.min(r, this.rows - 1 - r) / (this.rows / 2);
      const edge = Math.min(ex, ey * 1.1);
      const thr = amp * 1.5 - edge;
      const n = h2(cx * 71 + r * 13, this.seed);
      if (n > thr) continue;
      const a = clamp01((thr - n) * 4);
      const ch = chars[(h2(cx + r * 5, tick + ((n * 9) | 0)) * chars.length) | 0];
      const gx4 = (cx + .5) * this.cell;
      this.glyph(ch, gx4, (r + .5) * this.cell,
        this.ink(n * 300 + this.t * 45, 100, 58, hot, gx4), a);
    }
  }
}

/* ═══════════════════════════════════════════════════════════════════════
   ScapeIntro — the whole animation, with no framework attached.
   The tune panel drives this; production imports it on its own. Everything
   above this line (AsciiIntro, ButtonFx, the mark, the charsets) is already
   framework-free, so this file plus those is the entire runtime.
   ═══════════════════════════════════════════════════════════════════════ */
const DEFAULTS = {
  /* timing */
  style: 'decode', duration: 4.5, lift: 38, reveal: 86, ease: 'ease-in-out',
  /* mark */
  charset: 'ascii', palette: 'spectrum', zoom: 2, density: 4,
  spread: 16, stagger: 42, churn: 22, turns: 1.5, noise: 240,
  /* ignite */
  solidify: true, igniteStyle: 'bloom', igniteLen: 24, afterglow: 55,
  /* trip */
  trails: 18, bloom: 30, split: 34, drift: 40,
  /* background field */
  bg: 'flow', bgAmt: 34, bgSpeed: 100, bgScale: 2,
  bgColor: 'palette', bgHue: 200, bgPersist: false,
  /* pulse */
  pulse: 'rect', pulseEchoes: 3, pulseReach: 55, pulseThick: 1,
  pulseAmt: 80, pulseColor: 'palette', pulseHue: 200,
  /* parts — draw the pieces of the mark at different rates */
  partsOn: false,
  partDelay: { ring: 0, barTop: 14, barBottom: 22, stemLeft: 34,
               stemRight: 44, dotLeft: 62, dotRight: 78 },
  /* buttons */
  btnFx: 'scramble', btnInt: 80, btnSpeed: 1, btnIdle: 22, btnCharPx: 6,
  invert: true, btnMono: true, btnInvertMode: 'snap',
  btnAttack: 0.09, btnRelease: 0.22,
  /* behaviour */
  loop: false, skippable: true, pauseWhenHidden: true,
  reducedMotion: 'skip', once: false
};

/* used by the tune panel to group the copied config, and to render sections */
const CONFIG_GROUPS = [
  ['timing',     ['style', 'duration', 'lift', 'reveal', 'ease']],
  ['mark',       ['charset', 'palette', 'zoom', 'density', 'spread', 'stagger', 'churn', 'turns', 'noise']],
  ['ignite',     ['solidify', 'igniteStyle', 'igniteLen', 'afterglow']],
  ['trip',       ['trails', 'bloom', 'split', 'drift']],
  ['background', ['bg', 'bgAmt', 'bgSpeed', 'bgScale', 'bgColor', 'bgHue', 'bgPersist']],
  ['pulse',      ['pulse', 'pulseEchoes', 'pulseReach', 'pulseThick', 'pulseAmt', 'pulseColor', 'pulseHue']],
  ['parts',      ['partsOn', 'partDelay']],
  ['buttons',    ['btnFx', 'btnInt', 'btnSpeed', 'btnIdle', 'btnCharPx', 'invert',
                  'btnMono', 'btnInvertMode', 'btnAttack', 'btnRelease']],
  ['behaviour',  ['loop', 'skippable', 'pauseWhenHidden', 'reducedMotion', 'once']]
];

const ASCII_IDS = ['converge', 'vortex', 'warp', 'rain', 'decode', 'storm', 'glitch', 'quantum'];
const isAscii = id => ASCII_IDS.indexOf(id) >= 0;

class ScapeIntro {
  constructor(root, config) {
    this.root = root;
    this.cfg = ScapeIntro.merge(config);
    this.timers = [];
    this.fx = [];
    this.canvas = root.querySelector('.ascii-canvas');
    if (!this.canvas) {
      this.canvas = document.createElement('canvas');
      this.canvas.className = 'ascii-canvas';
      root.appendChild(this.canvas);
    }
    this.engine = new AsciiIntro(this.canvas);
  }

  /* shallow merge everywhere except partDelay, which is a nested object and
     would otherwise be replaced wholesale by a partial config */
  static merge(config) {
    const out = Object.assign({}, DEFAULTS, config || {});
    out.partDelay = Object.assign({}, DEFAULTS.partDelay,
      (config && config.partDelay) || {});
    return out;
  }

  mount() {
    this.syncButtons();
    this.onResize = () => {
      for (const f of this.fx) f.dirty = true;
      this.apply();
      const e = this.engine;
      if (e && e.cfg && e.running) {
        e.cfg.zoom = this.effZoom();
        e.layout(); e.build();
      }
    };
    window.addEventListener('resize', this.onResize);

    /* a hidden tab throttles rAF to a crawl, so the intro would otherwise be
       half-finished and jerky when the visitor comes back — hold it instead */
    this.onVis = () => {
      if (!this.cfg.pauseWhenHidden) return;
      if (document.hidden) this.pause(); else this.resume();
    };
    document.addEventListener('visibilitychange', this.onVis);

    this.onSkip = ev => {
      if (!this.cfg.skippable || !this.engine.running) return;
      /* never let the tune panel's own clicks cut the animation short */
      if (ev.target && ev.target.closest && ev.target.closest('[data-scape-ui]')) return;
      this.skip();
    };
    for (const t of ['pointerdown', 'keydown', 'wheel'])
      window.addEventListener(t, this.onSkip, { passive: true });

    this.tickButtons = this.tickButtons.bind(this);
    this.btnLast = performance.now();
    this.btnRaf = requestAnimationFrame(this.tickButtons);

    this.apply();
    /* two frames of slack so the stylesheet has landed before the mark is
       measured; the engine re-anchors on its own after that anyway */
    requestAnimationFrame(() => requestAnimationFrame(() => {
      this.apply();
      if (this.shouldSkipEntirely()) this.finish();
      else this.replay();
    }));
    return this;
  }

  destroy() {
    this.clearTimers();
    if (this.engine) this.engine.halt();
    if (this.btnRaf) cancelAnimationFrame(this.btnRaf);
    window.removeEventListener('resize', this.onResize);
    document.removeEventListener('visibilitychange', this.onVis);
    for (const t of ['pointerdown', 'keydown', 'wheel'])
      window.removeEventListener(t, this.onSkip);
    for (const f of this.fx) f.destroy();
    this.fx = [];
  }

  /* honour the OS motion setting, and optionally only ever play once */
  shouldSkipEntirely() {
    const c = this.cfg;
    if (c.reducedMotion === 'skip' && window.matchMedia
        && window.matchMedia('(prefers-reduced-motion: reduce)').matches) return true;
    if (c.once) {
      const key = 'scape-intro-seen';
      try {
        const store = c.once === 'local' ? localStorage : sessionStorage;
        if (store.getItem(key)) return true;
        store.setItem(key, '1');
      } catch (e) { /* private mode — just play it */ }
    }
    return false;
  }

  syncButtons() {
    const btns = [...this.root.querySelectorAll('.button')];
    if (btns.length === this.fx.length && this.fx.every((f, i) => f.btn === btns[i])) return;
    for (const f of this.fx) f.destroy();
    this.fx = btns.map(b => new ButtonFx(b));
  }
  tickButtons(now) {
    let dt = (now - this.btnLast) / 1000; this.btnLast = now;
    if (dt > 0.1) dt = 0.1;
    const c = this.cfg;
    const bc = this.btnCfg || (this.btnCfg = {});
    bc.variant = c.btnFx; bc.intensity = c.btnInt / 100; bc.speed = c.btnSpeed;
    bc.idle = c.btnIdle / 100; bc.invert = c.invert; bc.mono = c.btnMono;
    bc.charPx = c.btnCharPx; bc.charset = c.charset; bc.palette = c.palette;
    bc.invertMode = c.btnInvertMode; bc.attack = c.btnAttack; bc.release = c.btnRelease;
    for (const f of this.fx) f.frame(dt, bc);
    this.btnRaf = requestAnimationFrame(this.tickButtons);
  }
  pulseButtons() { for (const f of this.fx) { f.pulse = 1; f.scram = 1; f.t = 0; } }

  clearTimers() { for (const t of this.timers) clearTimeout(t); this.timers = []; }
  after(ms, fn) { this.timers.push(setTimeout(fn, ms)); }

  /* the mark is a multiplier of its 176x144 base, but never larger than the
     viewport can hold — canvas and DOM both read this so they stay in step */
  effZoom() {
    const w = Math.max(1, window.innerWidth), h = Math.max(1, window.innerHeight);
    return Math.max(0.6, Math.min(this.cfg.zoom, w * 0.74 / 176, h * 0.56 / 144));
  }

  apply() {
    const r = this.root; if (!r) return;
    const c = this.cfg, ascii = isAscii(c.style);
    r.dataset.style = c.style;
    r.dataset.mode = ascii ? 'ascii' : 'classic';
    r.style.setProperty('--splash-duration', c.duration + 's');
    r.style.setProperty('--splash-ease', c.ease);
    r.style.setProperty('--lift', c.lift + 'px');
    r.style.setProperty('--mark-zoom', ascii ? this.effZoom() : 1);
    r.style.setProperty('--ui-delay', (c.duration * c.reveal / 100).toFixed(2) + 's');
    r.style.setProperty('--ui-dur', (c.duration * 0.2).toFixed(2) + 's');
  }

  /* The mark's final on-screen rect, from a throwaway probe mirroring .logo's
     own CSS — so the ascii mark and the DOM mark can never disagree. Pass a
     `anchor()` in the config to drive it from different markup. */
  markRect() {
    if (this.cfg.anchor) return this.cfg.anchor();
    const box = this.root.querySelector('.logoBox') || this.root;
    const probe = document.createElement('div');
    probe.style.cssText = 'box-sizing:content-box;position:absolute;top:50vh;left:50%;padding:16px;' +
      'border:16px solid transparent;width:112px;height:80px;' +
      'transform:translate(-88px,-72px);visibility:hidden;pointer-events:none';
    box.appendChild(probe);
    const b = probe.getBoundingClientRect();
    probe.remove();
    const z = this.effZoom();
    return { x: b.left + b.width / 2 - 88 * z, y: b.top + b.height / 2 - 72 * z };
  }

  replay() {
    this.clearTimers();
    const r = this.root; if (!r) return;
    const c = this.cfg, ascii = isAscii(c.style);

    r.classList.remove('is-lift', 'is-done');
    this.lastLogoOpacity = null;
    const lg = r.querySelector('.logo');
    if (lg) lg.style.opacity = ascii ? '0' : '';

    const els = r.querySelectorAll('.logo, .logo > div, header, .intro');
    els.forEach(e => { e.style.animation = 'none'; });
    void r.offsetWidth;
    els.forEach(e => { e.style.animation = ''; });

    const ms = c.duration * 1000;
    if (ascii) {
      this.engine.start({
        variant: c.style, durMs: ms,
        anchor: () => this.markRect(), markX: 0, markY: 0,
        zoom: this.effZoom(), density: c.density,
        charset: c.charset, palette: c.palette,
        spread: c.spread * c.density / 2, stagger: c.stagger / 100, churn: c.churn,
        turns: c.turns, noise: c.noise,
        trails: c.trails / 100, bloom: c.bloom / 100, split: c.split / 100,
        drift: c.drift,
        bg: c.bg, bgAmt: c.bgAmt / 100, bgSpeed: c.bgSpeed / 100,
        bgScale: c.bgScale, bgColor: c.bgColor, bgHue: c.bgHue, bgPersist: c.bgPersist,
        pulse: c.pulse, pulseEchoes: c.pulseEchoes, pulseReach: c.pulseReach / 100,
        pulseThick: c.pulseThick, pulseAmt: c.pulseAmt / 100,
        pulseColor: c.pulseColor, pulseHue: c.pulseHue,
        solidify: c.solidify, churnRate: 1,
        partsOn: c.partsOn, partDelay: c.partDelay,
        afterglow: c.afterglow / 100, igniteStyle: c.igniteStyle,
        tConv: Math.max(0.35, T_IGN - c.igniteLen / 100),
        onIgnite: (g, markFade) => this.onIgnite(g, markFade)
      });
      this.after(ms * T_LIFT, () => r.classList.add('is-lift'));
    } else {
      this.engine.halt();
    }
    this.after(ms * c.reveal / 100 + 120, () => this.pulseButtons());
    this.after(ms + 40, () => { r.classList.add('is-done'); if (this.cfg.onDone) this.cfg.onDone(); });
    if (c.loop) this.after(ms + 900, () => this.replay());
  }

  /* By the time the ignite is nearly done the ascii mark IS a solid white
     block of exactly the DOM mark's geometry, so fading the real one in over
     that last stretch is invisible — nothing pops. */
  onIgnite(g, markFade) {
    const lg = this.root.querySelector('.logo'); if (!lg) return;
    const o = this.cfg.solidify
      ? Math.max(clamp01((g - 0.78) / 0.22), 1 - markFade)
      : 1 - markFade;
    if (o !== this.lastLogoOpacity) { lg.style.opacity = o; this.lastLogoOpacity = o; }
  }

  /* fast-forward rather than cut: jump to just before the hand-off and let the
     ignite and reveal play out quickly, so a skip still lands on the logo */
  skip() {
    const e = this.engine;
    if (!e.running || !e.cfg) return;
    const el = (performance.now() - e.t0) / e.cfg.durMs;
    if (el > 0.8) return;
    this.clearTimers();
    e.t0 = performance.now() - 0.8 * e.cfg.durMs;
    const r = this.root, ms = e.cfg.durMs;
    r.style.setProperty('--ui-delay', '0.05s');
    r.style.setProperty('--ui-dur', '0.3s');
    const els = r.querySelectorAll('header, .intro');
    els.forEach(x => { x.style.animation = 'none'; });
    void r.offsetWidth;
    els.forEach(x => { x.style.animation = ''; });
    this.after(ms * 0.1, () => r.classList.add('is-lift'));
    this.after(ms * 0.22, () => {
      r.classList.add('is-done');
      if (this.cfg.onDone) this.cfg.onDone();
    });
  }

  /* land on the finished state with no animation at all */
  finish() {
    this.clearTimers();
    this.engine.halt();
    const r = this.root;
    r.classList.add('is-lift', 'is-done', 'no-intro');
    const lg = r.querySelector('.logo');
    if (lg) lg.style.opacity = '1';
    if (this.cfg.onDone) this.cfg.onDone();
  }

  pause() {
    const e = this.engine;
    if (e.running && e.raf) { cancelAnimationFrame(e.raf); e.raf = 0; this.pausedAt = performance.now(); }
    if (this.btnRaf) { cancelAnimationFrame(this.btnRaf); this.btnRaf = 0; }
  }
  resume() {
    const e = this.engine;
    if (e.running && !e.raf) {
      if (this.pausedAt) { const d = performance.now() - this.pausedAt; e.t0 += d; e.last = performance.now(); }
      e.raf = requestAnimationFrame(e.step);
    }
    this.pausedAt = 0;
    if (!this.btnRaf) { this.btnLast = performance.now(); this.btnRaf = requestAnimationFrame(this.tickButtons); }
  }

  /* patch the config; `replay` false applies without restarting the intro */
  set(patch, replay) {
    if (patch && patch.partDelay) patch = Object.assign({}, patch,
      { partDelay: Object.assign({}, this.cfg.partDelay, patch.partDelay) });
    Object.assign(this.cfg, patch);
    this.apply();
    if (replay !== false) this.replay();
  }

  /* the config as pasteable source, grouped and commented */
  serialize() {
    const c = this.cfg;
    const q = v => typeof v === 'string' ? "'" + v + "'"
      : (v && typeof v === 'object')
        ? '{ ' + Object.keys(v).map(k => k + ': ' + v[k]).join(', ') + ' }'
        : String(v);
    let out = '{\n';
    CONFIG_GROUPS.forEach(([name, keys], gi) => {
      out += '  /* ' + name + ' */\n';
      keys.forEach(k => { out += '  ' + k + ': ' + q(c[k]) + ',\n'; });
      if (gi < CONFIG_GROUPS.length - 1) out += '\n';
    });
    return out.replace(/,\n$/, '\n') + '}';
  }
}

  var api = {
    mount: function (el, config) {
      var node = typeof el === 'string' ? document.querySelector(el) : el;
      if (!node) throw new Error('SCAPE.mount: no element matched ' + el);
      var c = new ScapeIntro(node, config).mount();
      api._last = c;            /* what the tune panel attaches to */
      return c;
    },
    defaults: DEFAULTS,
    ScapeIntro: ScapeIntro,
    _last: null
  };
  return api;
});
