/* SCAPE intro config — generated by the tune panel (press T).
   Load this before scape-intro.js, then: SCAPE.mount('.stage', SCAPE_CONFIG) */
window.SCAPE_CONFIG = {
  /* timing */
  style: 'quantum',
  duration: 6,
  lift: 40,
  reveal: 95,
  ease: 'ease-in-out',

  /* mark */
  charset: 'ascii',
  palette: 'spectrum',
  zoom: 1.7,
  density: 6,
  spread: 4,
  stagger: 50,
  churn: 6,
  turns: 0,
  noise: 100,

  /* ignite */
  solidify: true,
  igniteStyle: 'wave',
  igniteLen: 33,
  afterglow: 55,

  /* trip */
  trails: 80,
  bloom: 10,
  split: 50,
  drift: 0,

  /* background */
  bg: 'life',
  bgAmt: 10,
  bgSpeed: 100,
  bgScale: 1,
  bgColor: 'palette',
  bgHue: 200,
  bgPersist: false,

  /* pulse */
  pulse: 'scan',
  pulseEchoes: 3,
  pulseReach: 40,
  pulseThick: 3,
  pulseAmt: 80,
  pulseColor: 'palette',
  pulseHue: 200,

  /* parts */
  partsOn: false,
  partDelay: { ring: 0, barTop: 14, barBottom: 22, stemLeft: 34, stemRight: 44, dotLeft: 62, dotRight: 78 },

  /* buttons */
  btnFx: 'plasma',
  btnInt: 50,
  btnSpeed: 3,
  btnIdle: 22,
  btnCharPx: 6,
  invert: true,
  btnMono: false,
  btnInvertMode: 'none',
  btnAttack: 0.06,
  btnRelease: 0.06,

  /* popups */
  popupOn: true,
  popupW: 40,
  popupX: 104,
  popupY: 76,
  popupScale: 1,
  popupDur: 1,
  popupFlash: 0.26,
  popupStagger: 0.56,

  /* behaviour */
  loop: false,
  skippable: true,
  pauseWhenHidden: true,
  reducedMotion: 'skip',
  once: false
};
